import type { Metadata } from "next";
import Link from "next/link";
import { Brand,BrandMark } from "@/components/ui/brand";

export const metadata:Metadata={robots:{index:false,follow:false}};
const benefits=["Plan auction targets and budgets","Run live auctions with your team","Manage squads, fixtures and duties"];

export default function AuthLayout({children}:{children:React.ReactNode}){return <main className="min-h-dvh bg-canvas lg:grid lg:grid-cols-[minmax(0,1fr)_minmax(30rem,.9fr)]"><section className="relative flex min-h-dvh flex-col px-4 py-5 sm:px-8 lg:px-12"><header className="mx-auto flex w-full max-w-2xl items-center justify-between"><Brand/><Link href="/" className="min-h-11 rounded-xl px-3 py-3 text-sm font-bold text-slate-600 hover:bg-white hover:text-pitch">Back to Home</Link></header><div className="flex flex-1 items-center justify-center py-10 sm:py-14">{children}</div><p className="mx-auto w-full max-w-2xl text-center text-xs text-slate-500 sm:text-left">© {new Date().getFullYear()} Squad Planner</p></section><aside className="relative hidden min-h-dvh overflow-hidden bg-ink text-white lg:flex lg:flex-col"><div className="absolute -right-24 -top-20 size-80 rounded-full border border-white/10"/><div className="absolute -right-8 -top-4 size-52 rounded-full border border-lime/25"/><div className="absolute -bottom-28 -left-24 size-80 rounded-full bg-pitch/35 blur-3xl"/><div className="relative flex h-full flex-1 flex-col justify-between p-10 xl:p-14"><Link href="/" className="inline-flex w-fit items-center gap-3 rounded-xl font-bold"><span className="grid size-10 place-items-center rounded-xl bg-white/10 text-lime"><BrandMark/></span>Cricket team command centre</Link><div className="my-12 max-w-xl"><span className="inline-flex rounded-full bg-lime px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-ink">Built for auction day</span><h2 className="mt-7 text-4xl font-black leading-[1.08] tracking-[-.045em] xl:text-5xl">Every team decision, in one focused workspace.</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-300">Prepare your player strategy, respond quickly during the live auction and carry the same squad into tournament management.</p><ul className="mt-8 space-y-4">{benefits.map(item=><li key={item} className="flex items-center gap-3 text-sm font-semibold text-slate-200"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-lime/15 text-lime" aria-hidden="true">✓</span>{item}</li>)}</ul></div><div className="grid grid-cols-3 gap-3" aria-label="Squad Planner capabilities"><Feature value="A/B/C" label="Auction plans"/><Feature value="Live" label="Team updates"/><Feature value="All" label="Screen sizes"/></div></div></aside></main>}
function Feature({value,label}:{value:string;label:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><p className="text-xl font-black text-lime">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>}
