import Link from "next/link";
import { requireTournamentAdmin } from "@/lib/tournament/admin-access";

export default async function TournamentAdminPage({params}:{params:Promise<{tournamentId:string}>}){
  const{tournamentId}=await params;const{user,supabase}=await requireTournamentAdmin(tournamentId);
  const[{data:tournament},{data:teams},{data:members}]=await Promise.all([supabase.from("tournaments").select("*").eq("id",tournamentId).single(),supabase.from("teams").select("*").eq("tournament_id",tournamentId).order("name"),supabase.from("team_members").select("team_id,user_id,role")]);
  if(!tournament)return null;const managed=teams??[],access=(members??[]).filter(member=>managed.some(team=>team.id===member.team_id));
  const withoutCaptain=managed.filter(team=>!access.some(member=>member.team_id===team.id&&member.role==="captain")).length,withoutVice=managed.filter(team=>!access.some(member=>member.team_id===team.id&&member.role==="vice_captain")).length;
  return <main className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><p className="team-accent-text text-sm font-bold">Tournament Admin</p><h1 className="text-3xl font-black">{tournament.name}</h1><p className="mt-1 text-slate-500">{tournament.start_date} – {tournament.end_date??"Open-ended"}</p><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Teams" value={managed.length}/><Metric label="Users" value={new Set(access.map(item=>item.user_id)).size}/><Metric label="Without Captain" value={withoutCaptain}/><Metric label="Without Vice Captain" value={withoutVice}/></section><div className="mt-8 flex items-center justify-between"><h2 className="text-2xl font-black">Tournament teams</h2><Link href={`/tournaments/${tournamentId}/admin/teams`} className="team-primary rounded-xl px-4 py-3 font-bold">Create Team</Link></div><section className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{managed.map(team=>{const teamAccess=access.filter(item=>item.team_id===team.id),captain=teamAccess.some(item=>item.role==="captain"),vice=teamAccess.some(item=>item.role==="vice_captain"),canOpen=teamAccess.some(item=>item.user_id===user.id);return <article key={team.id} className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="text-xl font-black">{team.name}</h3><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt>Captain</dt><dd className="font-bold">{captain?"✓ Assigned":"Setup required"}</dd><dt>Vice Captain</dt><dd className="font-bold">{vice?"✓ Assigned":"Not assigned"}</dd><dt>Team Users</dt><dd className="font-bold">{teamAccess.length}</dd><dt>Squad Size</dt><dd className="font-bold">{team.squad_size}</dd></dl><div className="mt-4 flex gap-2"><Link href={`/tournaments/${tournamentId}/admin/users?team=${team.id}`} className="rounded-lg border px-3 py-2 text-sm font-bold">Manage Access</Link>{canOpen?<Link href={`/teams/${team.id}`} className="rounded-lg border px-3 py-2 text-sm font-bold">Open Team</Link>:<span className="rounded-lg bg-slate-100 px-3 py-2 text-xs text-slate-500">Private strategy protected</span>}</div></article>})}</section></main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
