"use server";
import { revalidatePath } from "next/cache";
import { requireTeamAccess } from "@/lib/planning/access";
import { createClient } from "@/lib/supabase/server";
import { normalisePlayerName } from "@/types/planning";
import type { DuplicateDecision, ImportRow, ValidatedImportRow } from "@/types/player-import";
import type { AvailabilityStatus } from "@/types/database";

function priorityValue(value:string){const normal=value.trim().toLowerCase();const labels:Record<string,number>={"highest priority":1,highest:1,"1":1,high:2,"2":2,medium:3,"3":3,low:4,"4":4,backup:5,"5":5};return normal?labels[normal]??Number.NaN:null}
function availabilityValue(value:string):AvailabilityStatus|null{const normal=value.trim().toLowerCase();if(!normal)return "unknown";if(["full","full league","yes"].includes(normal))return "full";if(["partial","part"].includes(normal))return "partial";if(["unknown","not known","no"].includes(normal))return "unknown";return null}

export async function validateImport(teamId:string,rows:ImportRow[]):Promise<{rows:ValidatedImportRow[];error?:string}>{await requireTeamAccess(teamId,true);if(!Array.isArray(rows)||rows.length>2000)return{rows:[],error:"Import must contain between 1 and 2,000 rows."};const supabase=await createClient();const[{data:existing},{data:buckets}]=await Promise.all([supabase.from("players").select("id,name").eq("team_id",teamId),supabase.from("auction_buckets").select("id,name").eq("team_id",teamId)]);const existingMap=new Map((existing??[]).map(p=>[normalisePlayerName(p.name),p.id]));const incoming=new Map<string,number>();const bucketNames=new Set((buckets??[]).map(b=>normalisePlayerName(b.name)));return{rows:rows.map(row=>{const errors:string[]=[];const normalized=normalisePlayerName(row.name);if(!row.name.trim())errors.push("Player name is required.");if(normalized){incoming.set(normalized,(incoming.get(normalized)??0)+1)}const priority=priorityValue(row.priority);if(row.priority&&priority===null||Number.isNaN(priority))errors.push("Priority must be 1–5 or a supported label.");const price=Number(row.expectedPrice||0);if(!Number.isFinite(price)||price<0)errors.push("Expected price must be 0 or greater.");const availability=availabilityValue(row.availability);if(!availability)errors.push("Availability must be Full League, Partial or Unknown.");if(row.availableMatches&&(!Number.isInteger(Number(row.availableMatches))||Number(row.availableMatches)<0))errors.push("Available matches must be a whole number of 0 or greater.");if(row.bucket&&!bucketNames.has(normalisePlayerName(row.bucket)))errors.push(`Bucket “${row.bucket}” does not exist.`);return{...row,existingPlayerId:existingMap.get(normalized)??null,errors}}).map(row=>({...row,errors:(incoming.get(normalisePlayerName(row.name))??0)>1?[...row.errors,"Duplicate name appears in this import file."]:row.errors}))}}

function toRecord(row:ValidatedImportRow,bucketMap:Map<string,string>){const availability=availabilityValue(row.availability)??"unknown";return{name:row.name.trim(),role:row.role.trim()||null,priority:priorityValue(row.priority),expected_price:Number(row.expectedPrice||0),availability_status:availability,available_matches:availability==="partial"&&row.availableMatches?Number(row.availableMatches):null,availability_notes:row.availabilityNotes.trim()||null,notes:row.notes.trim()||null,bucket_id:row.bucket?bucketMap.get(normalisePlayerName(row.bucket))??null:null}}
export async function confirmImport(teamId:string,rows:ValidatedImportRow[],decisions:Record<number,DuplicateDecision>){await requireTeamAccess(teamId,true);const fresh=await validateImport(teamId,rows);if(fresh.error||fresh.rows.some(r=>r.errors.length))return{ok:false,message:"Resolve all validation errors before importing."};const supabase=await createClient();const{data:buckets}=await supabase.from("auction_buckets").select("id,name").eq("team_id",teamId);const bucketMap=new Map((buckets??[]).map(b=>[normalisePlayerName(b.name),b.id]));let imported=0,updated=0,skipped=0;for(const row of fresh.rows){const record=toRecord(row,bucketMap);if(row.existingPlayerId){const decision=decisions[row.rowNumber]??"skip";if(decision==="skip"){skipped++;continue}if(decision==="replace"){const{error}=await supabase.from("players").update(record).eq("team_id",teamId).eq("id",row.existingPlayerId);if(error)return{ok:false,message:`Row ${row.rowNumber}: ${error.message}`};updated++;continue}}const{error}=await supabase.from("players").insert({team_id:teamId,...record});if(error)return{ok:false,message:`Row ${row.rowNumber}: ${error.message}`};imported++}revalidatePath(`/teams/${teamId}/players`);return{ok:true,message:`Import complete: ${imported} added, ${updated} updated, ${skipped} skipped.`}}
