"use server";
import{revalidatePath}from"next/cache";
import{requirePermission}from"@/lib/permissions/server";
import{createClient}from"@/lib/supabase/server";
import type{AuctionLifecycle,AuctionStatus}from"@/types/database";
import type{AuctionMutationResult}from"@/types/auction";

export async function changeAuctionStatus(teamId:string,playerId:string,expectedStatus:AuctionStatus,newStatus:AuctionStatus,soldPrice=0,overrideSquad=false,overrideBucket=false):Promise<AuctionMutationResult>{
  await requirePermission({module:"team_auction",action:"manage",scopeType:"team",scopeId:teamId,mode:"mutation"});
  if(!Number.isFinite(soldPrice)||soldPrice<0)return{ok:false,code:"error",message:"Sold price must be 0 or greater."};
  const supabase=await createClient(),{data:team}=await supabase.from("teams").select("auction_status").eq("id",teamId).maybeSingle();
  if(team?.auction_status==="completed")return{ok:false,code:"forbidden",message:"Reopen the auction before changing player decisions."};
  const{data,error}=await supabase.rpc("rbac_update_player_auction_status",{p_team_id:teamId,p_player_id:playerId,p_expected_status:expectedStatus,p_new_status:newStatus,p_sold_price:soldPrice,p_override_squad_limit:overrideSquad,p_override_bucket_max:overrideBucket});
  if(error){const message=error.message;if(message.includes("AUCTION_CONFLICT"))return{ok:false,code:"conflict",message:"This player's auction status changed on another device. The latest status has been loaded."};if(message.includes("SQUAD_LIMIT"))return{ok:false,code:"squad_limit",message:"The squad limit has been reached. Confirm again to continue."};if(message.includes("BUCKET_MAX"))return{ok:false,code:"bucket_max",message:"This bucket is at its planned maximum. Confirm again to continue."};if(message.includes("PERMISSION_DENIED")||message.includes("READ_ONLY"))return{ok:false,code:"forbidden",message:"You have read-only auction access."};return{ok:false,code:"error",message:"The auction decision could not be saved."}}
  revalidatePath(`/teams/${teamId}/auction`);revalidatePath(`/teams/${teamId}/squad`);return{ok:true,player:data};
}
export async function changeAuctionLifecycle(teamId:string,expected:AuctionLifecycle,next:AuctionLifecycle){await requirePermission({module:"team_auction",action:"manage",scopeType:"team",scopeId:teamId,mode:"mutation"});const supabase=await createClient();const{data,error}=await supabase.rpc("rbac_update_auction_lifecycle",{p_team_id:teamId,p_expected_status:expected,p_new_status:next});if(error)return{ok:false,message:error.message.includes("CONFLICT")?"Auction lifecycle changed on another device.":"Unable to update the auction lifecycle."};revalidatePath(`/teams/${teamId}/auction`);revalidatePath(`/teams/${teamId}/squad`);return{ok:true,status:data};}
export async function placeCentralAuctionBid(teamId:string,auctionId:string,_state:{message:string;ok?:boolean},data:FormData){await requirePermission({module:"team_auction",action:"bid",scopeType:"team",scopeId:teamId,mode:"mutation"});const amount=Number(String(data.get("amount")??""));if(!Number.isFinite(amount)||amount<0)return{message:"Enter a valid bid amount."};const supabase=await createClient();const{error}=await supabase.rpc("rbac_place_tournament_bid",{p_auction_id:auctionId,p_team_id:teamId,p_amount:amount});if(error){if(error.message.includes("BID_TOO_LOW"))return{message:"Your bid must exceed the current bid by the minimum increment."};if(error.message.includes("BID_EXCEEDS_BUDGET"))return{message:"This bid exceeds your remaining auction budget."};if(error.message.includes("BID_EXCEEDS_BUCKET_MAX")||error.message.includes("TEAM_BUCKET_FULL"))return{message:"This team has reached the tournament bucket maximum."};return{message:"The bid could not be accepted. Reload the latest auction state."}}revalidatePath(`/teams/${teamId}/auction`);return{ok:true,message:"Bid accepted."}}
