"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { signOut } from "@/app/(auth)/actions";

const modules=[["","Dashboard"],["players","Players"],["buckets","Buckets"],["planning","Planning"],["auction","Auction"],["squad","Squad"],["tournament","Tournament"],["opportunities","Opportunities"],["duties","Volunteer Duties"],["reports","Reports"]] as const;
function teamIdFrom(pathname:string){const match=pathname.match(/^\/teams\/([^/]+)/);return match?.[1]&&match[1]!=="new"?match[1]:null}
export function AuthenticatedMobileMenu({displayName}:{displayName:string}){const path=usePathname(),teamId=teamIdFrom(path),[open,setOpen]=useState(false);useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);const links=teamId?modules.map(([suffix,label])=>({label,href:`/teams/${teamId}${suffix?`/${suffix}`:""}`})):[{label:"Dashboard",href:"/dashboard"},{label:"Create Team",href:"/teams/new"}];return <><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="account-mobile-menu" aria-label={open?"Close application menu":"Open application menu"} className="grid size-11 place-items-center rounded-xl border bg-white lg:hidden"><svg viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d={open?"M6 6l12 12M18 6 6 18":"M4 7h16M4 12h16M4 17h16"}/></svg></button>{open?<div className="fixed inset-0 top-16 z-50 bg-ink/30 lg:hidden" onClick={()=>setOpen(false)}><aside id="account-mobile-menu" className="ml-auto flex h-full w-[min(23rem,92vw)] flex-col overflow-y-auto bg-white p-4 shadow-2xl" onClick={e=>e.stopPropagation()}><p className="px-3 py-2 text-xs font-black uppercase tracking-wider text-pitch">{teamId?"Team workspace":"My account"}</p><nav aria-label="Application mobile navigation">{links.map(link=><Link key={link.href} href={link.href} onClick={()=>setOpen(false)} className={`flex min-h-12 items-center rounded-xl px-3 font-bold ${path===link.href?"bg-pitch/10 text-pitch":"text-slate-700 hover:bg-slate-50"}`}>{link.label}</Link>)}</nav><div className="mt-auto border-t pt-4"><p className="truncate px-3 text-sm font-bold">{displayName}</p><Link href="/profile" onClick={()=>setOpen(false)} className="mt-2 flex min-h-12 items-center rounded-xl px-3 font-semibold">My Profile</Link><Link href="/dashboard" onClick={()=>setOpen(false)} className="flex min-h-12 items-center rounded-xl px-3 font-semibold">My Teams</Link><form action={signOut}><button className="min-h-12 w-full rounded-xl px-3 text-left font-semibold text-red-700">Logout</button></form></div></aside></div>:null}</>}

export function AuthenticatedBottomNav(){const path=usePathname(),teamId=teamIdFrom(path);const links=teamId?[{l:"Dashboard",h:`/teams/${teamId}`},{l:"Players",h:`/teams/${teamId}/players`},{l:"Auction",h:`/teams/${teamId}/auction`},{l:"Squad",h:`/teams/${teamId}/squad`}]:[{l:"Dashboard",h:"/dashboard"},{l:"Teams",h:"/dashboard"},{l:"Profile",h:"/profile"}];return <nav aria-label="Mobile quick navigation" className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden"><ul className={`grid ${teamId?"grid-cols-5":"grid-cols-3"}`}>{links.map((x,i)=><li key={`${x.h}-${i}`}><Link href={x.h} className={`flex min-h-12 items-center justify-center rounded-xl px-1 text-center text-[.69rem] font-bold ${path===x.h?"bg-pitch/10 text-pitch":"text-slate-500"}`}>{x.l}</Link></li>)}{teamId?<li><button type="button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="min-h-12 w-full rounded-xl text-[.69rem] font-bold text-slate-500">More ↑</button></li>:null}</ul></nav>}

export function DesktopTeamLinks(){const path=usePathname(),teamId=teamIdFrom(path);if(!teamId)return null;return <><p className="mb-2 mt-8 px-3 text-[.65rem] font-black uppercase tracking-[.18em] text-slate-500">Team workspace</p>{modules.map(([suffix,label])=>{const href=`/teams/${teamId}${suffix?`/${suffix}`:""}`;return <Link key={href} href={href} aria-current={path===href?"page":undefined} className={`flex min-h-10 items-center rounded-xl px-3 text-sm font-semibold ${path===href?"bg-white/10 text-white":"text-slate-300 hover:bg-white/10 hover:text-white"}`}>{label}</Link>})}</>}
