"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { signOut } from "@/app/(auth)/actions";
import { isNavigationActive } from "@/lib/navigation/active";
import { permissionGranted, teamModuleRegistry, type PermissionMap } from "@/lib/permissions/registry";

export const teamModules=teamModuleRegistry;

function teamIdFrom(pathname:string){const match=pathname.match(/^\/teams\/([^/]+)/);return match?.[1]&&match[1]!=="new"?match[1]:null}
export function TeamNavigationLinks({collapsed=false,onNavigate,permissionsByTeam={}}:{collapsed?:boolean;onNavigate?:()=>void;permissionsByTeam?:Record<string,PermissionMap>}){
  const pathname=usePathname(),teamId=teamIdFrom(pathname);
  const links=teamId?teamModules.filter(module=>permissionGranted(permissionsByTeam[teamId],module.key,"view")).map(module=>({label:module.label,icon:module.icon,href:`/teams/${teamId}${module.suffix?`/${module.suffix}`:""}`})):[{label:"My Teams",icon:"dashboard" as const,href:"/dashboard"},{label:"Create Team",icon:"add" as const,href:"/teams/new"}];
  return <nav aria-label="Team workspace navigation" className="space-y-1">{links.map(link=>{const active=isNavigationActive(pathname,link.href,{exact:link.label==="Dashboard"||link.href==="/dashboard"});return <Link key={link.href} href={link.href} onClick={onNavigate} aria-current={active?"page":undefined} aria-label={collapsed?link.label:undefined} title={collapsed?link.label:undefined} className={`relative flex min-h-11 items-center rounded-xl transition-colors ${collapsed?"justify-center px-2":"gap-3 px-3"} ${active?"before:absolute before:left-0 before:h-6 before:w-1 before:rounded-r-full before:bg-[var(--team-primary)]":"text-slate-300 hover:bg-white/10 hover:text-white"}`} style={active?{color:"var(--team-primary)",backgroundColor:"var(--team-primary-soft)"}:undefined}><NavigationIcon name={link.icon}/>{!collapsed?<span className="truncate text-sm font-semibold">{link.label}</span>:null}</Link>})}</nav>;
}

export function AuthenticatedMobileMenu({displayName,permissionsByTeam={}}:{displayName:string;permissionsByTeam?:Record<string,PermissionMap>}){
  const pathname=usePathname(),[open,setOpen]=useState(false),panelRef=useRef<HTMLElement>(null),closeRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!open)return;document.body.style.overflow="hidden";const prior=document.activeElement as HTMLElement|null;requestAnimationFrame(()=>closeRef.current?.focus());function keydown(event:KeyboardEvent){if(event.key==="Escape")setOpen(false);if(event.key!=="Tab"||!panelRef.current)return;const focusable=[...panelRef.current.querySelectorAll<HTMLElement>('a[href],button:not([disabled])')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}document.addEventListener("keydown",keydown);return()=>{document.body.style.overflow="";document.removeEventListener("keydown",keydown);prior?.focus()}},[open]);
  return <><button type="button" onClick={()=>setOpen(true)} aria-expanded={open} aria-controls="account-mobile-menu" aria-label="Open navigation" className="grid size-11 place-items-center rounded-xl border bg-white xl:hidden"><MenuIcon/></button>{open?<div className="fixed inset-0 top-16 z-50 bg-ink/40 xl:hidden" onClick={()=>setOpen(false)}><aside ref={panelRef} id="account-mobile-menu" role="dialog" aria-modal="true" aria-label="Application navigation" className="flex h-full w-[min(23rem,92vw)] flex-col overflow-y-auto bg-ink p-4 text-white shadow-2xl" onClick={event=>event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><p className="text-xs font-black uppercase tracking-[.16em] text-lime">Team workspace</p><button ref={closeRef} type="button" onClick={()=>setOpen(false)} aria-label="Close navigation" className="grid size-11 place-items-center rounded-xl bg-white/10"><CloseIcon/></button></div><TeamNavigationLinks permissionsByTeam={permissionsByTeam} onNavigate={()=>setOpen(false)}/><div className="mt-auto border-t border-white/10 pt-4"><p className="truncate px-3 text-sm font-bold">{displayName}</p><Link href="/profile" onClick={()=>setOpen(false)} className={`mt-2 flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold ${pathname==="/profile"?"bg-white/15 text-white":"text-slate-300 hover:bg-white/10"}`}><NavigationIcon name="profile"/>Profile</Link><form action={signOut}><button className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm font-semibold text-slate-300 hover:bg-white/10"><NavigationIcon name="logout"/>Logout</button></form></div></aside></div>:null}</>;
}

export function AuthenticatedBottomNav({permissionsByTeam={}}:{permissionsByTeam?:Record<string,PermissionMap>}){const pathname=usePathname(),teamId=teamIdFrom(pathname);if(!teamId)return null;const links=teamModules.filter(module=>["","players","auction","squad"].includes(module.suffix)&&permissionGranted(permissionsByTeam[teamId],module.key,"view")).map(module=>({label:module.label,href:`/teams/${teamId}${module.suffix?`/${module.suffix}`:""}`,icon:module.icon}));if(!links.length)return null;return <nav aria-label="Mobile quick navigation" className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur md:hidden"><ul className="grid" style={{gridTemplateColumns:`repeat(${links.length},minmax(0,1fr))`}}>{links.map(link=>{const active=isNavigationActive(pathname,link.href,{exact:link.label==="Dashboard"});return <li key={link.href}><Link href={link.href} aria-current={active?"page":undefined} className={`flex min-h-12 flex-col items-center justify-center gap-1 rounded-xl px-1 text-[.67rem] font-bold ${active?"bg-pitch/10 text-pitch":"text-slate-500"}`}><NavigationIcon name={link.icon} small/>{link.label}</Link></li>})}</ul></nav>}

type IconName=(typeof teamModules)[number]["icon"]|"add"|"profile"|"logout";
const paths:Record<IconName,string>={dashboard:"M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10 0h6v6h-6v-6Z",players:"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m7-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87",buckets:"M4 7h16M4 12h16M4 17h16",planning:"M4 19.5V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v14.5l-4-2-4 2-4-2-4 2Z",auction:"m14 5 5 5M12 7l5 5m-9.5 1.5 3 3L5 22H2v-3l5.5-5.5ZM15 4l2-2 5 5-2 2",squad:"M12 3 4 7v5c0 5 3.4 8.6 8 9 4.6-.4 8-4 8-9V7l-8-4Z",tournament:"M6 2v4m12-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v15H3V6a2 2 0 0 1 2-2Z",opportunities:"m3 17 6-6 4 4 8-9M15 6h6v6",duties:"M9 11l3 3L22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11",reports:"M4 20V10m6 10V4m6 16v-7m5 7H2",add:"M12 5v14M5 12h14",profile:"M20 21a8 8 0 0 0-16 0M12 13a5 5 0 1 0 0-10 5 5 0 0 0 0 10Z",logout:"M10 17l5-5-5-5m5 5H3m12-9h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"};
export function NavigationIcon({name,small=false}:{name:IconName;small?:boolean}){return <svg viewBox="0 0 24 24" className={small?"size-4":"size-5 shrink-0"} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>}
function MenuIcon(){return <svg viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>}
function CloseIcon(){return <svg viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg>}
