"use client";

import Link from "next/link";
import { useState } from "react";
import { signOut } from "@/app/(auth)/actions";
import { AuthenticatedBottomNav, AuthenticatedMobileMenu, NavigationIcon, TeamNavigationLinks } from "@/components/layout/authenticated-navigation";
import { Brand, BrandMark } from "@/components/ui/brand";
import { TeamSwitcher } from "@/components/layout/team-switcher";
import { usePathname } from "next/navigation";
import type { PermissionMap } from "@/lib/permissions/registry";

export function DashboardShell({children,displayName,teams,adminTournaments,permissionsByTeam,isSuperAdmin=false}:{children:React.ReactNode;displayName:string;teams:{id:string;name:string}[];adminTournaments:{id:string;name:string}[];permissionsByTeam:Record<string,PermissionMap>;isSuperAdmin?:boolean}){
  const [expanded,setExpanded]=useState(false);
  const pathname=usePathname(),currentTeamId=pathname.match(/^\/teams\/([^/]+)/)?.[1]??null;
  return <div className={`min-h-dvh bg-canvas xl:grid ${expanded?"xl:grid-cols-[17rem_1fr]":"xl:grid-cols-[5rem_1fr]"}`}>
    <aside className={`hidden border-r border-white/10 bg-ink px-3 py-4 text-white transition-[width] xl:flex xl:flex-col ${expanded?"w-[17rem]":"w-20"}`}>
      <div className={`flex items-center ${expanded?"justify-between":"flex-col gap-3"}`}>
        {expanded?<Brand href="/dashboard" inverted/>:<Link href="/dashboard" aria-label="Squad Planner home" title="Squad Planner" className="grid size-11 place-items-center rounded-xl bg-white/10 text-lime"><BrandMark/></Link>}
        <button type="button" onClick={()=>setExpanded(value=>!value)} aria-label={expanded?"Collapse navigation":"Expand navigation"} aria-expanded={expanded} title={expanded?"Collapse navigation":"Expand navigation"} className="grid size-11 shrink-0 place-items-center rounded-xl bg-white/10 text-white hover:bg-white/15"><svg viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button>
      </div>
      <div className="mt-6"><TeamNavigationLinks permissionsByTeam={permissionsByTeam} collapsed={!expanded}/>{isSuperAdmin?<div className="mt-4 border-t border-white/10 pt-4"><Link href="/admin" title={!expanded?"Super Admin":undefined} aria-label={!expanded?"Super Admin":undefined} className={`flex min-h-11 items-center rounded-xl text-lime hover:bg-white/10 ${expanded?"gap-3 px-3":"justify-center px-2"}`}><NavigationIcon name="dashboard"/>{expanded?<span className="text-sm font-bold">Super Admin</span>:null}</Link></div>:null}{adminTournaments.length?<div className="mt-4 border-t border-white/10 pt-4">{expanded?<p className="px-3 text-xs font-black uppercase text-slate-400">Tournament Admin</p>:null}{adminTournaments.map(tournament=><Link key={tournament.id} href={`/tournaments/${tournament.id}/admin`} title={!expanded?`Admin: ${tournament.name}`:undefined} aria-label={!expanded?`Tournament Admin: ${tournament.name}`:undefined} className={`mt-1 flex min-h-11 items-center rounded-xl text-slate-300 hover:bg-white/10 hover:text-white ${expanded?"gap-3 px-3":"justify-center px-2"}`}><NavigationIcon name="tournament"/>{expanded?<span className="truncate text-sm font-semibold">{tournament.name}</span>:null}</Link>)}</div>:null}</div>
      <div className="mt-auto border-t border-white/10 pt-4">{expanded?<p className="truncate px-3 text-sm font-bold">{displayName}</p>:null}<Link href="/profile" aria-label={!expanded?"Profile":undefined} title={!expanded?"Profile":undefined} className={`mt-2 flex min-h-11 items-center rounded-xl text-sm text-slate-300 hover:bg-white/10 ${expanded?"gap-3 px-3":"justify-center px-2"}`}><NavigationIcon name="profile"/>{expanded?<span>Profile</span>:null}</Link><form action={signOut}><button aria-label={!expanded?"Logout":undefined} title={!expanded?"Logout":undefined} className={`flex min-h-11 w-full items-center rounded-xl text-left text-sm text-slate-300 hover:bg-white/10 ${expanded?"gap-3 px-3":"justify-center px-2"}`}><NavigationIcon name="logout"/>{expanded?<span>Logout</span>:null}</button></form></div>
    </aside>
      <div className="min-w-0"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b bg-white/95 px-4 backdrop-blur-xl sm:px-6 xl:px-8"><div className="xl:hidden"><Brand href="/dashboard"/></div><div className="hidden items-center gap-3 xl:flex"><p className="text-sm font-bold text-slate-600">Tournament workspace</p><TeamSwitcher teams={teams} currentTeamId={currentTeamId}/></div><div className="flex items-center gap-2"><div className="xl:hidden"><TeamSwitcher teams={teams} currentTeamId={currentTeamId}/></div><details className="relative hidden xl:block"><summary className="min-h-10 cursor-pointer list-none rounded-xl border bg-white px-4 py-2 text-sm font-semibold">{displayName}</summary><div className="absolute right-0 mt-2 w-48 rounded-xl border bg-white p-2 shadow-xl"><Link href="/profile" className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50">My Profile</Link><Link href="/dashboard" className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-50">My Teams</Link><form action={signOut}><button className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50">Logout</button></form></div></details><AuthenticatedMobileMenu permissionsByTeam={permissionsByTeam} displayName={displayName}/></div></header><main id="main-content" className="pb-24 md:pb-0">{children}</main><AuthenticatedBottomNav permissionsByTeam={permissionsByTeam}/></div>
  </div>;
}
