"use server";
import {revalidatePath} from "next/cache";
import {requireTournamentAdmin as requireHardTournamentAdmin} from "@/lib/tournament/admin-access";
import {requirePermission} from "@/lib/permissions/server";
async function requireTournamentAdmin(tournamentId:string){await requirePermission({module:"auction_control",action:"manage",scopeType:"tournament",scopeId:tournamentId,mode:"mutation"});return requireHardTournamentAdmin(tournamentId)}
const text=(d:FormData,k:string)=>String(d.get(k)??"").trim();
export async function saveAuction(tournamentId:string,_state:{message:string;ok?:boolean},data:FormData){const{user,supabase}=await requireTournamentAdmin(tournamentId);const increment=Number(text(data,"increment")||1);if(!Number.isFinite(increment)||increment<=0)return{message:"Minimum bid increment must be greater than 0."};const payload={tournament_id:tournamentId,name:text(data,"name")||"Tournament Auction",auction_date:text(data,"date")||null,start_time:text(data,"time")||null,location:text(data,"location")||null,meeting_link:text(data,"meetingLink")||null,minimum_bid_increment:increment,status:"scheduled",created_by:user.id};const existing=text(data,"auctionId");const{error}=existing?await supabase.from("tournament_auctions").update(payload).eq("id",existing).eq("tournament_id",tournamentId):await supabase.from("tournament_auctions").insert(payload);if(!error)revalidatePath(`/tournaments/${tournamentId}/admin/auction`);return{ok:!error,message:error?"We couldn't save the auction.":"Auction schedule saved."}}
export async function createTournamentBucket(tournamentId:string,_state:{message:string;ok?:boolean},data:FormData){const{supabase}=await requireTournamentAdmin(tournamentId);const name=text(data,"name"),min=Number(text(data,"minimum")||0),max=text(data,"maximum")?Number(text(data,"maximum")):null,maxBid=text(data,"maxBid")?Number(text(data,"maxBid")):null;if(!name||min<0||(max!==null&&max<min)||(maxBid!==null&&maxBid<0))return{message:"Check the bucket name and limits."};const{error}=await supabase.from("tournament_auction_buckets").insert({tournament_id:tournamentId,name,minimum_players_per_team:min,maximum_players_per_team:max,max_player_bid:maxBid});if(!error)revalidatePath(`/tournaments/${tournamentId}/admin/auction`);return{ok:!error,message:error?"We couldn't create the auction bucket.":"Auction bucket created."}}
export async function pickRandomPlayer(tournamentId:string,bucketId:string){const{supabase}=await requireTournamentAdmin(tournamentId);const{data:auction}=await supabase.from("tournament_auctions").select("id").eq("tournament_id",tournamentId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!auction)return{ok:false,data:undefined,message:"Schedule the auction before selecting a player."};const{data,error}=await supabase.rpc("pick_random_auction_player",{p_auction_id:auction.id,p_bucket_id:bucketId});return{ok:!error,data:data??undefined,message:error?"No eligible player is available in this bucket.":"Random player selected."}}
export async function startPlayerBidding(tournamentId:string,auctionId:string,playerId:string){const{supabase}=await requireTournamentAdmin(tournamentId);const{error}=await supabase.rpc("set_tournament_auction_player",{p_auction_id:auctionId,p_player_id:playerId,p_expected_status:"ready"});if(!error)revalidatePath(`/tournaments/${tournamentId}/admin/auction`);return{ok:!error,message:error?"The player state changed. Reload and try again.":"Bidding started."}}
export async function confirmWinningBid(tournamentId:string,auctionId:string,bidId:string){const{supabase}=await requireTournamentAdmin(tournamentId);const{error}=await supabase.rpc("confirm_tournament_sale",{p_auction_id:auctionId,p_bid_id:bidId});if(!error)revalidatePath(`/tournaments/${tournamentId}/admin/auction`);return{ok:!error,message:error?"The winning bid changed. Reload the latest bids.":"Winner confirmed atomically."}}
export async function markUnsold(tournamentId:string,auctionId:string,playerId:string){const{supabase}=await requireTournamentAdmin(tournamentId);const{error}=await supabase.rpc("mark_tournament_player_unsold",{p_auction_id:auctionId,p_player_id:playerId});if(!error)revalidatePath(`/tournaments/${tournamentId}/admin/auction`);return{ok:!error,message:error?"We couldn't mark this player unsold.":"Player marked unsold."}}
