"use client";

import Papa from "papaparse";
import { useState, useTransition } from "react";
import { readSheet } from "read-excel-file/browser";

import { importFixtures } from "@/app/(protected)/teams/[teamId]/tournament/actions";
import { fixtureDuplicateKey, parseFixtureRows, type FixtureImportRow } from "@/lib/tournament/fixture-import";

type Cell = string | number | boolean | Date | null;
type Existing = { match_date:string;match_time:string|null;opponent_name:string };
type Decision = "skip"|"update"|"import";

export function FixtureImport({teamId,tournamentId,existing}:{teamId:string;tournamentId:string;existing:Existing[]}){
  const[open,setOpen]=useState(false),[rows,setRows]=useState<FixtureImportRow[]>([]),[filename,setFilename]=useState(""),[message,setMessage]=useState(""),[decisions,setDecisions]=useState<Record<number,Decision>>({});const[pending,start]=useTransition();
  const existingKeys=new Set(existing.map(row=>fixtureDuplicateKey({date:row.match_date,time:row.match_time?.slice(0,5)??null,opponent:row.opponent_name})));
  const duplicates=rows.filter(row=>existingKeys.has(fixtureDuplicateKey(row)));
  async function choose(file:File){setMessage("");setRows([]);if(file.size>5*1024*1024){setMessage("The schedule file must be 5 MB or smaller.");return}const ext=file.name.split(".").pop()?.toLowerCase();if(ext==="xls"){setMessage("Please convert this file to .xlsx or .csv before uploading.");return}if(!ext||!["xlsx","csv"].includes(ext)){setMessage("Choose an .xlsx or .csv schedule.");return}try{let matrix:Cell[][];if(ext==="xlsx")matrix=await readSheet(file) as Cell[][];else matrix=await new Promise((resolve,reject)=>Papa.parse<Cell[]>(file,{skipEmptyLines:true,complete:r=>r.errors.length?reject(new Error()):resolve(r.data),error:reject}));const parsed=parseFixtureRows(matrix);if(parsed.missing.length)throw new Error(`Required column missing: ${parsed.missing.join(", ")}`);if(!parsed.rows.length)throw new Error("No fixture rows found.");setRows(parsed.rows);setFilename(file.name);setDecisions(Object.fromEntries(parsed.rows.filter(row=>existingKeys.has(fixtureDuplicateKey(row))).map(row=>[row.rowNumber,"skip"])))}catch(error){setMessage(error instanceof Error?error.message:"We couldn't read that schedule.")}}
  function confirm(){if(!rows.some(row=>!row.errors.length)){setMessage("There are no valid fixtures to import.");return}start(async()=>{const result=await importFixtures(teamId,tournamentId,filename,rows.map(row=>({...row,duplicateAction:decisions[row.rowNumber]??"import"})));if(!result.ok)setMessage(result.message??"Import failed.");else{setMessage(`Import complete: ${result.imported} added, ${result.updated} updated, ${result.skipped} skipped, ${result.failed} failed.`);setRows([])}})}
  return <section className="mt-5 rounded-2xl border bg-white p-4 sm:p-5"><button type="button" onClick={()=>setOpen(value=>!value)} className="team-primary min-h-11 rounded-xl px-4 text-sm font-bold">{open?"Close schedule import":"Import Schedule"}</button>{open?<div className="mt-4"><label className="block text-sm font-bold">Excel or CSV schedule<input type="file" accept=".xlsx,.csv" onChange={event=>event.target.files?.[0]&&choose(event.target.files[0])} className="mt-2 block w-full rounded-xl border p-3 text-sm"/></label><p className="mt-2 text-xs text-slate-500">Required: Date and Opponent. Optional: Match Number, Time, Venue, Round and Notes.</p>{message?<p role="status" className="mt-3 rounded-xl bg-slate-50 p-3 text-sm font-semibold">{message}</p>:null}{rows.length?<><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Summary label="Rows" value={rows.length}/><Summary label="Valid" value={rows.filter(row=>!row.errors.length).length}/><Summary label="Invalid" value={rows.filter(row=>row.errors.length).length}/><Summary label="Duplicates" value={duplicates.length}/></div><div className="mt-4 space-y-2">{rows.map(row=>{const duplicate=existingKeys.has(fixtureDuplicateKey(row));return <article key={row.rowNumber} className={`rounded-xl border p-3 ${row.errors.length?"border-red-200 bg-red-50":"bg-white"}`}><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><strong>{row.opponent||`Row ${row.rowNumber}`}</strong><p className="text-xs text-slate-500">{row.date||"Invalid date"} {row.time??""} · {row.venue??"Venue TBD"}</p>{row.errors.length?<p className="mt-1 text-xs font-bold text-red-700">{row.errors.join(" · ")}</p>:duplicate?<p className="mt-1 text-xs font-bold text-amber-700">Potential duplicate fixture</p>:null}</div>{duplicate?<select aria-label={`Duplicate action for row ${row.rowNumber}`} value={decisions[row.rowNumber]??"skip"} onChange={event=>setDecisions(current=>({...current,[row.rowNumber]:event.target.value as Decision}))} className="min-h-11 rounded-xl border px-3 text-sm"><option value="skip">Skip</option><option value="update">Update Existing</option><option value="import">Import Anyway</option></select>:null}</div></article>})}</div><button disabled={pending} onClick={confirm} className="team-primary mt-4 min-h-12 w-full rounded-xl px-5 font-bold disabled:opacity-50">{pending?"Importing...":"Confirm Import"}</button></>:null}</div>:null}</section>
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
