"use client";

import { useMemo, useState } from "react";
import type { PlayerWithBucket } from "@/lib/planning/queries";
import { filterPlanningPlayers } from "@/lib/planning/search";
import type { AuctionBucket } from "@/types/planning";
import { AVAILABILITY_LABELS,formatMoney,PLAYER_ROLES,PRIORITY_LABELS } from "@/types/planning";

export function PlayerPlanSearch({players,buckets,selectedIds,planLabel,action}:{players:PlayerWithBucket[];buckets:AuctionBucket[];selectedIds:string[];planLabel:string;action:(formData:FormData)=>Promise<void>}){
  const[query,setQuery]=useState(""),[bucketId,setBucketId]=useState(""),[role,setRole]=useState(""),[priority,setPriority]=useState(""),[availability,setAvailability]=useState(""),[active,setActive]=useState(0);
  const selected=new Set(selectedIds);
  const results=useMemo(()=>filterPlanningPlayers(players,{query,bucketId,role,priority,availability}).slice(0,20),[players,query,bucketId,role,priority,availability]);
  const show=Boolean(query||bucketId||role||priority||availability);
  function keyDown(event:React.KeyboardEvent<HTMLInputElement>){if(!show||!results.length)return;if(event.key==="ArrowDown"){event.preventDefault();setActive(index=>Math.min(results.length-1,index+1))}if(event.key==="ArrowUp"){event.preventDefault();setActive(index=>Math.max(0,index-1))}if(event.key==="Enter"){event.preventDefault();document.getElementById(`plan-result-${results[active]?.id}`)?.focus()}}
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Find a player</h2><p className="mt-1 text-sm text-slate-500">Search and add directly to Plan {planLabel}.</p><label className="mt-4 block text-sm font-bold">Player name<input value={query} onChange={event=>{setQuery(event.target.value);setActive(0)}} onKeyDown={keyDown} placeholder="Start typing a player name" autoComplete="off" aria-controls="planning-player-results" className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-3"/></label><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2"><Select label="Bucket" value={bucketId} set={setBucketId} options={buckets.map(bucket=>[bucket.id,bucket.name])}/><Select label="Role" value={role} set={setRole} options={PLAYER_ROLES.map(value=>[value,value])}/><Select label="Priority" value={priority} set={setPriority} options={Object.entries(PRIORITY_LABELS)}/><Select label="Availability" value={availability} set={setAvailability} options={Object.entries(AVAILABILITY_LABELS)}/></div>{show?<div id="planning-player-results" role="listbox" aria-label={`Players for Plan ${planLabel}`} className="mt-3 max-h-[28rem] space-y-2 overflow-y-auto rounded-xl border bg-slate-50 p-2">{results.map((player,index)=>{const already=selected.has(player.id);return <article key={player.id} role="option" aria-selected={index===active} className={`rounded-xl border bg-white p-3 ${index===active?"team-border":"border-slate-200"}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between lg:flex-col xl:flex-row"><div><strong>{player.name}</strong><p className="mt-1 text-xs text-slate-500">{player.role??"No role"} · {player.auction_buckets?.name??"Unassigned"}</p><p className="mt-1 text-xs text-slate-600">{player.priority?PRIORITY_LABELS[player.priority]:"Not ranked"} · {AVAILABILITY_LABELS[player.availability_status]} · Expected {formatMoney(player.expected_price)}</p></div>{already?<span className="team-soft rounded-full border px-3 py-2 text-xs font-bold">Already in Plan {planLabel}</span>:<form action={action}><input type="hidden" name="playerId" value={player.id}/><button id={`plan-result-${player.id}`} className="team-primary min-h-11 rounded-xl px-3 text-sm font-bold">Add to Plan {planLabel}</button></form>}</div></article>})}{!results.length?<p className="p-5 text-center text-sm text-slate-500">No players match this search.</p>:null}</div>:<p className="mt-4 rounded-xl border border-dashed p-4 text-sm text-slate-500">Type a name or choose filters to find players.</p>}</section>;
}

function Select({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:readonly (readonly [string,string])[]}){return <label className="text-xs font-bold text-slate-600">{label}<select value={value} onChange={event=>set(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-2 text-sm"><option value="">All {label.toLowerCase()}</option>{options.map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>}
