"use client";
import {useActionState,useState,useTransition} from "react";
import {addRegistrationField,createRegistrationForm,regenerateRegistrationLink,updateRegistrationStatus,type RegistrationActionState} from "@/app/(protected)/tournaments/[tournamentId]/admin/registration/actions";
import {SubmitButton} from "@/components/forms/submit-button";
type FormRow={id:string;title:string;description:string|null;instructions:string|null;status:"draft"|"open"|"closed"};type FieldRow={id:string;label:string;field_key:string;field_type:string;required:boolean;display_order:number};const initial:RegistrationActionState={message:""};
export function RegistrationBuilder({tournamentId,form,fields}:{tournamentId:string;form:FormRow|null;fields:FieldRow[]}){
 const[createState,createAction]=useActionState(createRegistrationForm.bind(null,tournamentId),initial);const[fieldState,fieldAction]=useActionState(form?addRegistrationField.bind(null,tournamentId,form.id):async()=>initial,initial);const[notice,setNotice]=useState("");const[pending,start]=useTransition();
 if(!form)return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Create registration form</h2><p className="mt-1 text-sm text-slate-600">Start with safe default player fields, then customise the form.</p><form action={createAction} className="mt-5 grid gap-4"><label className="grid gap-1 text-sm font-semibold">Title<input name="title" className="rounded-xl border p-3" required/></label><label className="grid gap-1 text-sm font-semibold">Description<textarea name="description" className="rounded-xl border p-3"/></label><label className="grid gap-1 text-sm font-semibold">Instructions<textarea name="instructions" className="rounded-xl border p-3"/></label><SubmitButton>Create form</SubmitButton>{createState.message&&<p className="text-sm">{createState.message}</p>}{createState.publicUrl&&<code className="break-all rounded-lg bg-slate-100 p-3 text-xs">{createState.publicUrl}</code>}</form></section>;
 const run=(fn:()=>Promise<{message:string;publicUrl?:string}>)=>start(async()=>{const result=await fn();setNotice(result.publicUrl??result.message)});
 return <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-emerald-700">{form.status}</p><h2 className="text-xl font-bold">{form.title}</h2><p className="text-sm text-slate-600">{form.description}</p></div><div className="flex gap-2"><button disabled={pending} className="rounded-xl border px-3 py-2" onClick={()=>run(()=>regenerateRegistrationLink(tournamentId,form.id))}>Regenerate link</button><button disabled={pending} className="rounded-xl bg-emerald-700 px-3 py-2 text-white" onClick={()=>run(()=>updateRegistrationStatus(tournamentId,form.id,form.status==="open"?"closed":"open"))}>{form.status==="open"?"Close":"Open"}</button></div></div>{notice&&<div className="mt-4 break-all rounded-xl bg-emerald-50 p-3 text-sm">{notice}</div>}<div className="mt-6 space-y-2">{fields.map((field,index)=><div key={field.id} className="flex items-center justify-between rounded-xl border p-3"><div><strong>{index+1}. {field.label}</strong><p className="text-xs text-slate-500">{field.field_type} · {field.field_key}</p></div><span className="text-xs font-semibold">{field.required?"Required":"Optional"}</span></div>)}</div></section><form action={fieldAction} className="h-fit rounded-2xl border bg-white p-5"><h3 className="font-bold">Add custom field</h3><div className="mt-4 grid gap-3"><input name="label" placeholder="Field label" className="rounded-xl border p-3" required/><input name="key" placeholder="field_key" className="rounded-xl border p-3" required/><select name="fieldType" className="rounded-xl border p-3"><option value="short_text">Short text</option><option value="long_text">Long text</option><option value="number">Number</option><option value="dropdown">Dropdown</option><option value="radio">Radio</option><option value="checkbox">Checkbox</option><option value="date">Date</option><option value="yes_no">Yes / No</option></select><input name="options" placeholder="Options, comma separated" className="rounded-xl border p-3"/><input name="order" type="number" defaultValue={fields.length+1} className="rounded-xl border p-3"/><label className="flex gap-2 text-sm"><input type="checkbox" name="required"/> Required</label><SubmitButton>Add field</SubmitButton>{fieldState.message&&<p className="text-sm">{fieldState.message}</p>}</div></form></div>;
}
