"use client";
import {useState,useTransition} from "react";
import Papa from "papaparse";
import readXlsxFile from "read-excel-file/browser";
import {importTournamentTeams,type TeamImportRow} from "@/app/(protected)/tournaments/[tournamentId]/admin/teams/import/actions";
const aliases:Record<string,keyof TeamImportRow>={"team name":"teamName",name:"teamName","primary colour":"primaryColour","primary color":"primaryColour","secondary colour":"secondaryColour","captain name":"captainName","captain email":"captainEmail","vice captain name":"viceCaptainName","vice captain email":"viceCaptainEmail","squad size":"squadSize","auction budget":"auctionBudget","total auction budget":"auctionBudget"};
const normal=(v:unknown)=>String(v??"").trim().toLowerCase().replace(/\s+/g," ");
export function TeamImport({tournamentId}:{tournamentId:string}){
 const[rows,setRows]=useState<TeamImportRow[]>([]),[error,setError]=useState(""),[result,setResult]=useState("");const[pending,start]=useTransition();
 async function parse(file:File){setError("");if(file.size>5*1024*1024){setError("The team file must be 5 MB or smaller.");return}if(!/\.(xlsx|csv)$/i.test(file.name)){setError("Please upload an .xlsx or .csv file.");return}try{let matrix:unknown[][];if(file.name.toLowerCase().endsWith(".xlsx"))matrix=(await readXlsxFile(file)) as unknown as unknown[][];else matrix=Papa.parse<string[]>(await file.text(),{skipEmptyLines:true}).data;const headers=matrix[0].map(normal),map=headers.map(h=>aliases[h]);if(!map.includes("teamName")){setError("Required column missing: Team Name");return}setRows(matrix.slice(1).map(cells=>{const base:TeamImportRow={teamName:"",primaryColour:"#15803d",secondaryColour:"",captainName:"",captainEmail:"",viceCaptainName:"",viceCaptainEmail:"",squadSize:18,auctionBudget:0};map.forEach((key,index)=>{if(!key)return;const raw=cells[index];if(key==="squadSize"||key==="auctionBudget")base[key]=Number(raw)||0;else base[key]=String(raw??"").trim()});return base}).filter(x=>x.teamName))}catch{setError("We couldn't read this file. Check its format and try again.")}}
 return <div className="space-y-5"><label className="grid gap-2 rounded-2xl border bg-white p-6 font-bold">Choose tournament team file<input type="file" accept=".xlsx,.csv" onChange={e=>e.target.files?.[0]&&parse(e.target.files[0])}/><span className="text-xs font-normal text-slate-500">Required: Team Name. Optional: colours, Captain/Vice Captain names and emails, Squad Size, Auction Budget.</span></label>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{rows.length>0&&<section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Preview · {rows.length} teams</h2><button disabled={pending} onClick={()=>start(async()=>{const r=await importTournamentTeams(tournamentId,rows);setResult(r.message)})} className="rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white">{pending?"Importing…":"Confirm import"}</button></div><div className="mt-4 divide-y">{rows.map((row,index)=><div key={`${row.teamName}-${index}`} className="grid gap-1 py-3 sm:grid-cols-3"><strong>{row.teamName}</strong><span>Captain: {row.captainName||"Not assigned"}</span><span>Squad: {row.squadSize} · Budget: {row.auctionBudget}</span></div>)}</div></section>}{result&&<p className="rounded-xl bg-emerald-50 p-3">{result}</p>}</div>;
}
