"use server";
import {createHash,randomBytes} from "node:crypto";
import {revalidatePath} from "next/cache";
import {applicationOrigin} from "@/lib/auth/origin";
import {requireTournamentAdmin} from "@/lib/tournament/admin-access";
export type RegistrationActionState={ok?:boolean;message:string;publicUrl?:string};
const value=(data:FormData,key:string)=>String(data.get(key)??"").trim();
const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function createRegistrationForm(tournamentId:string,_state:RegistrationActionState,data:FormData):Promise<RegistrationActionState>{
 const{user,supabase}=await requireTournamentAdmin(tournamentId);const title=value(data,"title");if(!title)return{message:"Registration title is required."};const token=randomBytes(32).toString("base64url");
 const{data:form,error}=await supabase.from("registration_forms").insert({tournament_id:tournamentId,token_hash:hash(token),title,description:value(data,"description")||null,instructions:value(data,"instructions")||null,created_by:user.id}).select("id").single();if(error||!form)return{message:"We couldn't create the registration form."};
 const defaults=[{field_key:"name",field_type:"short_text",label:"Full Name",required:true,display_order:0},{field_key:"email",field_type:"email",label:"Email",required:true,display_order:1},{field_key:"phone",field_type:"phone",label:"Phone",required:false,display_order:2},{field_key:"role",field_type:"dropdown",label:"Player Role",required:true,display_order:3,options:["Batter","Wicketkeeper Batter","All-rounder","Bowler","Wicketkeeper","Other"]},{field_key:"availability",field_type:"radio",label:"Availability",required:false,display_order:4,options:["Full League","Partial","Unknown"]}];await supabase.from("registration_form_fields").insert(defaults.map(item=>({...item,form_id:form.id})));
 revalidatePath(`/tournaments/${tournamentId}/admin/registration`);return{ok:true,message:"Registration form created. Copy this link now; only its secure hash is stored.",publicUrl:`${applicationOrigin()}/register/${token}`};
}
export async function addRegistrationField(tournamentId:string,formId:string,_state:RegistrationActionState,data:FormData):Promise<RegistrationActionState>{
 const{supabase}=await requireTournamentAdmin(tournamentId);const label=value(data,"label"),fieldType=value(data,"fieldType"),key=value(data,"key").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");if(!label||!key)return{message:"Field label and key are required."};const options=value(data,"options").split(",").map(x=>x.trim()).filter(Boolean);const{error}=await supabase.from("registration_form_fields").insert({form_id:formId,field_key:key,field_type:fieldType,label,required:data.get("required")==="on",options,display_order:Number(value(data,"order")||100)});if(error)return{message:"We couldn't add that field. The key may already exist."};revalidatePath(`/tournaments/${tournamentId}/admin/registration`);return{ok:true,message:"Field added."};
}
export async function updateRegistrationStatus(tournamentId:string,formId:string,status:"draft"|"open"|"closed"){const{supabase}=await requireTournamentAdmin(tournamentId);const{error}=await supabase.from("registration_forms").update({status}).eq("id",formId).eq("tournament_id",tournamentId);if(!error)revalidatePath(`/tournaments/${tournamentId}/admin/registration`);return{ok:!error,message:error?"We couldn't update registration.":`Registration is now ${status}.`}}
export async function regenerateRegistrationLink(tournamentId:string,formId:string){const{supabase}=await requireTournamentAdmin(tournamentId);const token=randomBytes(32).toString("base64url");const{error}=await supabase.from("registration_forms").update({token_hash:hash(token)}).eq("id",formId).eq("tournament_id",tournamentId);if(error)return{ok:false,message:"We couldn't regenerate the link."};return{ok:true,message:"Old link disabled. Copy the new link now.",publicUrl:`${applicationOrigin()}/register/${token}`}}
