"use client";

import { useMemo, useState } from "react";

export type MatrixAction={action:string;action_name:string;allowed:boolean;custom:boolean};
export type MatrixModule={module:string;module_name:string;scope:string;sort_order:number;actions:MatrixAction[]};

export function PermissionMatrix({matrix,saveAction,resetAction}:{matrix:MatrixModule[];saveAction:(formData:FormData)=>Promise<void>;resetAction?:()=>Promise<void>}){
  const initial=useMemo(()=>Object.fromEntries(matrix.flatMap(module=>module.actions.map(action=>[`${module.module}:${action.action}`,action.allowed]))),[matrix]);
  const[values,setValues]=useState<Record<string,boolean>>(initial);
  const entries=matrix.flatMap(module=>module.actions.map(action=>({module:module.module,action:action.action,allowed:Boolean(values[`${module.module}:${action.action}`])})));
  function toggle(module:string,action:string){const key=`${module}:${action}`;setValues(current=>({...current,[key]:!current[key]}))}
  return <div className="space-y-4"><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>setValues(current=>({...current,...Object.fromEntries(matrix.map(module=>[`${module.module}:view`,true]))}))} className="rounded-xl border px-3 py-2 text-sm font-bold">Enable all View permissions</button>{resetAction?<form action={resetAction}><button className="rounded-xl border border-amber-300 px-3 py-2 text-sm font-bold text-amber-800" onClick={event=>{if(!confirm("Reset this role to the system defaults? User-specific overrides will remain."))event.preventDefault()}}>Reset to Default</button></form>:null}</div><form action={saveAction}><input type="hidden" name="permissions" value={JSON.stringify(entries)}/><div className="hidden overflow-x-auto rounded-2xl border bg-white md:block"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="sticky left-0 bg-slate-50 px-4 py-3 text-left">Module</th>{[...new Set(matrix.flatMap(module=>module.actions.map(action=>action.action)))].map(action=><th key={action} className="px-3 py-3 capitalize">{action.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{matrix.map(module=><tr key={module.module} className="border-t"><th className="sticky left-0 bg-white px-4 py-3 text-left">{module.module_name}</th>{[...new Set(matrix.flatMap(item=>item.actions.map(action=>action.action)))].map(action=>{const supported=module.actions.some(item=>item.action===action),checked=Boolean(values[`${module.module}:${action}`]);return <td key={action} className="px-3 py-3 text-center">{supported?<input type="checkbox" aria-label={`${module.module_name} ${action}`} checked={checked} onChange={()=>toggle(module.module,action)} className="size-5 accent-emerald-700"/>:<span aria-label="Not applicable" className="text-slate-300">—</span>}</td>})}</tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{matrix.map(module=><section key={module.module} className="rounded-2xl border bg-white p-4"><h3 className="font-black">{module.module_name}</h3><div className="mt-3 grid grid-cols-2 gap-2">{module.actions.map(action=><label key={action.action} className="flex min-h-11 items-center justify-between rounded-xl bg-slate-50 px-3 text-sm"><span>{action.action_name}</span><input type="checkbox" checked={Boolean(values[`${module.module}:${action.action}`])} onChange={()=>toggle(module.module,action.action)} className="size-5 accent-emerald-700"/></label>)}</div></section>)}</div><button className="mt-5 min-h-11 rounded-xl bg-emerald-700 px-5 font-bold text-white">Save Permissions</button></form></div>
}
