-- Phase 7: optional profile fields and private profile image storage.
alter table public.profiles add column display_name text,add column phone text,add column profile_image_path text,add column preferred_name text,add column bio text;
alter table public.profiles add constraint profiles_names_length_check check((display_name is null or char_length(display_name)<=100) and (preferred_name is null or char_length(preferred_name)<=100) and (full_name is null or char_length(full_name)<=150));
alter table public.profiles add constraint profiles_phone_length_check check(phone is null or char_length(phone)<=30);alter table public.profiles add constraint profiles_bio_length_check check(bio is null or char_length(bio)<=500);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('profile-assets','profile-assets',false,2097152,array['image/png','image/jpeg','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create or replace function private.user_id_from_profile_path(object_name text) returns uuid language plpgsql immutable set search_path='' as $$begin return split_part(object_name,'/',2)::uuid;exception when invalid_text_representation then return null;end;$$;
revoke all on function private.user_id_from_profile_path(text) from public;grant execute on function private.user_id_from_profile_path(text) to authenticated;
create policy "Users read own profile assets" on storage.objects for select to authenticated using(bucket_id='profile-assets' and split_part(name,'/',1)='users' and private.user_id_from_profile_path(name)=auth.uid());
create policy "Users upload own profile assets" on storage.objects for insert to authenticated with check(bucket_id='profile-assets' and split_part(name,'/',1)='users' and split_part(name,'/',3)='avatar' and private.user_id_from_profile_path(name)=auth.uid());
create policy "Users update own profile assets" on storage.objects for update to authenticated using(bucket_id='profile-assets' and private.user_id_from_profile_path(name)=auth.uid()) with check(bucket_id='profile-assets' and private.user_id_from_profile_path(name)=auth.uid());
create policy "Users delete own profile assets" on storage.objects for delete to authenticated using(bucket_id='profile-assets' and private.user_id_from_profile_path(name)=auth.uid());
create or replace function public.phase7_setup_status() returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('profile_fields',(select count(*)=5 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name in('display_name','phone','profile_image_path','preferred_name','bio')),'profile_bucket',exists(select 1 from storage.buckets where id='profile-assets' and public=false and file_size_limit=2097152),'profile_rls',(select relrowsecurity from pg_class where oid='public.profiles'::regclass));$$;revoke all on function public.phase7_setup_status() from public;grant execute on function public.phase7_setup_status() to anon,authenticated;
