"use client";

import Link from "next/link";
import { useActionState } from "react";
import { FormMessage } from "@/components/forms/form-message";
import { SubmitButton } from "@/components/forms/submit-button";
import { initialFormState,type FormState } from "@/types/forms";

type AuthAction=(state:FormState,formData:FormData)=>Promise<FormState>;
type Mode="login"|"signup"|"forgot"|"reset";
const content={login:{eyebrow:"Welcome back",title:"Sign in to Squad Planner",description:"Continue planning your cricket auction, squad and tournament.",button:"Sign In",pending:"Signing in…"},signup:{eyebrow:"Create your workspace",title:"Create your account",description:"Start building your team and preparing for auction day.",button:"Create Account",pending:"Creating account…"},forgot:{eyebrow:"Account recovery",title:"Reset your password",description:"Enter your email and we will send you a secure reset link.",button:"Send Reset Link",pending:"Sending link…"},reset:{eyebrow:"Choose a new password",title:"Set your new password",description:"Create a secure password with at least eight characters.",button:"Update Password",pending:"Updating password…"}} satisfies Record<Mode,{eyebrow:string;title:string;description:string;button:string;pending:string}>;

export function AuthForm({mode,action,callbackError=false}:{mode:Mode;action:AuthAction;callbackError?:boolean}){const[state,formAction]=useActionState(action,initialFormState),copy=content[mode],showEmail=mode!=="reset",showPassword=mode==="login"||mode==="signup"||mode==="reset";return <section className="w-full max-w-[29rem]" aria-labelledby="auth-title"><div className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-[0_24px_70px_-32px_rgba(15,23,42,.3)] sm:p-8"><div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-extrabold uppercase tracking-[.14em] text-pitch"><span className="size-2 rounded-full bg-pitch" aria-hidden="true"/>{copy.eyebrow}</div><h1 id="auth-title" className="mt-5 text-3xl font-black tracking-[-.035em] text-ink sm:text-[2.15rem]">{copy.title}</h1><p className="mt-3 max-w-sm text-sm leading-6 text-slate-600">{copy.description}</p><form action={formAction} className="mt-7 space-y-5">{mode==="signup"?<Field label="Full name" name="fullName" autoComplete="name" placeholder="Your full name" required/>:null}{showEmail?<Field label="Email address" name="email" type="email" inputMode="email" autoComplete="email" placeholder="you@example.com" required/>:null}{showPassword?<Field label={mode==="login"?"Password":"New password"} name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} placeholder="Enter your password" minLength={mode==="login"?undefined:8} hint={mode==="login"?undefined:"Use at least 8 characters."} required/>:null}{mode==="signup"||mode==="reset"?<Field label="Confirm password" name="confirmPassword" type="password" autoComplete="new-password" placeholder="Enter the password again" minLength={8} required/>:null}{callbackError?<FormMessage state={{status:"error",message:"That authentication link is invalid or has expired."}}/>:null}<FormMessage state={state}/><SubmitButton pendingLabel={copy.pending}>{copy.button}</SubmitButton></form><AuthLinks mode={mode}/></div><p className="mt-5 text-center text-xs leading-5 text-slate-500">Secure authentication powered by Supabase. Your team data remains protected by role-based access.</p></section>}
function Field({label,name,type="text",hint,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string;hint?:string}){const hintId=hint?`${name}-hint`:undefined;return <label className="block text-sm font-bold text-slate-700">{label}<input name={name} type={type} aria-describedby={hintId} {...props} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-slate-50/60 px-4 text-base text-ink shadow-sm outline-none transition placeholder:text-slate-400 hover:border-slate-400 focus:border-pitch focus:bg-white focus:ring-4 focus:ring-pitch/10"/>{hint?<span id={hintId} className="mt-1.5 block text-xs font-normal text-slate-500">{hint}</span>:null}</label>}
function AuthLinks({mode}:{mode:Mode}){if(mode==="login")return <div className="mt-6 space-y-5 text-sm"><div className="text-right"><Link className="font-bold text-pitch underline-offset-4 hover:underline" href="/forgot-password">Forgot password?</Link></div><div className="border-t pt-5 text-center text-slate-600">New to Squad Planner? <Link className="font-bold text-pitch underline-offset-4 hover:underline" href="/signup">Create Account</Link></div></div>;if(mode==="signup")return <div className="mt-6 border-t pt-5 text-center text-sm text-slate-600">Already have an account? <Link className="font-bold text-pitch underline-offset-4 hover:underline" href="/login">Sign In</Link></div>;return <div className="mt-6 border-t pt-5 text-center text-sm"><Link className="font-bold text-pitch underline-offset-4 hover:underline" href="/login">← Back to Sign In</Link></div>}
